In [2]:
pip install numpy

     |████████████████████████████████| 20.3MB 3.4MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/__init__.py'>

In [3]:
a=np.random.randn((10))

In [4]:
b=np.random.randn((10))

In [5]:
a

array([-3.50672028, -0.37763872, -2.0120602 , -0.10754325,  0.21543217,
       -0.53203532, -1.16653699,  0.14146454,  1.68606813, -1.82423857])

In [6]:
b

array([-0.46088202,  1.61773755, -0.00685633, -1.6079021 , -0.53522119,
        1.97501762, -0.25011839,  1.84711243, -0.9060471 , -0.08740677])

In [7]:
a+b

array([-3.9676023 ,  1.24009883, -2.01891653, -1.71544534, -0.31978901,
        1.4429823 , -1.41665538,  1.98857697,  0.78002103, -1.91164535])

In [8]:
a-b

array([-3.04583827, -1.99537626, -2.00520388,  1.50035885,  0.75065336,
       -2.50705294, -0.9164186 , -1.70564789,  2.59211523, -1.7368318 ])

In [9]:
a*b

array([ 1.61618431, -0.61092033,  0.01379534,  0.17291901, -0.11530386,
       -1.05077913,  0.29177235,  0.2613009 , -1.52765714,  0.15945081])

In [10]:
2*a

array([-7.01344056, -0.75527743, -4.0241204 , -0.21508649,  0.43086435,
       -1.06407064, -2.33307399,  0.28292907,  3.37213626, -3.64847714])

In [11]:
2/a

array([ -0.57033349,  -5.29606714,  -0.99400604, -18.59716989,
         9.28366435,  -3.75914893,  -1.71447628,  14.13781899,
         1.18619169,  -1.09634783])

In [12]:
a>0

array([False, False, False, False,  True, False, False,  True,  True,
       False])

In [13]:
a>1

array([False, False, False, False, False, False, False, False,  True,
       False])

In [14]:
a>8

array([False, False, False, False, False, False, False, False, False,
       False])

In [15]:
a>5

array([False, False, False, False, False, False, False, False, False,
       False])

In [16]:
x=[a>1]

In [17]:
x

[array([False, False, False, False, False, False, False, False,  True,
        False])]

In [18]:
a[a>1]

array([1.68606813])

In [19]:
a[a>0]

array([0.21543217, 0.14146454, 1.68606813])