In [1]:
pip install numpy

     |████████████████████████████████| 20.3MB 3.3MB/s eta 0:00:01    |████████████▉                   | 8.2MB 3.3MB/s eta 0:00:04
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
x=np.array([4,6,8,3,10])

In [3]:
np.sqrt(x)

array([2.        , 2.44948974, 2.82842712, 1.73205081, 3.16227766])

In [4]:
np.power(x,2)

array([ 16,  36,  64,   9, 100])

In [5]:
y=[4,7,6,2,9]

In [6]:
np.maximum(x,y)

array([ 4,  7,  8,  3, 10])