In [3]:
pip install numpy

     |████████████████████████████████| 20.3MB 3.3MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
x=np.array([1,7,9,8,5])

In [7]:
x[4]

5

In [8]:
x[x>5]

array([7, 9, 8])

In [ ]:
x[[3,2]]

# slicing

In [14]:
x=np.random.randn((10,10))

TypeError: 'tuple' object cannot be interpreted as an integer

In [15]:
x[0]

1

In [16]:
x[0][4]

IndexError: invalid index to scalar variable.

In [17]:
x[1:10:2]

array([7, 8])

In [18]:
x[::,0:4]

IndexError: too many indices for array

In [19]:
x=np.ones((5,5))

In [20]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
x[1:-1,1:-1]=0